import { Role, ROLES, ROUTES } from "@/constants";
import { clsx, type ClassValue } from "clsx";
import { twMerge } from "tailwind-merge";

// auto generated by shadcn
export function cn(...inputs: ClassValue[]) {
  return twMerge(clsx(inputs));
}

// Utils

const getDefaultRouteByRole = (
  role: Role,
  defaultRoute: string = ROUTES.private.dashboard,
) => {
  if (role === ROLES.ADMIN) return ROUTES.private.dashboard;
  if (role === ROLES.WORKER) return ROUTES.private.profile;
  if (role === ROLES.EXTERNAL) return ROUTES.private.workers;

  return defaultRoute;
};

export { getDefaultRouteByRole };
